### ISSUE TITLE
[beware] Do not choose date before 15 sep 2016

### ISSUE THREAD

**Issue by Zachariahz1** [metamutator/cities_in_motion#4]
![image](https://user-images.githubusercontent.com/95291163/144052491-480b4048-f068-4e6a-9348-daf8d4dc98f8.png)

**Comment by ztan88** [comment]
Now it gives warning upon invalid date

![image](https://user-images.githubusercontent.com/95233371/144074855-a91950dc-966f-4ea5-8c99-587f121f92b4.png)
